name: Automatically apply the access permit of BUPT

on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  Apply:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Automatic Apply
        run: |
          python autoApply.py
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            PHONE: ${{ secrets.PHONE }}
            TEACHER_UID: ${{ secrets.TEACHER_UID }}
            TEACHER_NAME: ${{ secrets.TEACHER_NAME }}
            TEACHER_NUMBER: ${{ secrets.TEACHER_NUMBER }}

      - name: First Retry
        if: ${{ failure() }}
        run: |
          python autoApply.py
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            PHONE: ${{ secrets.PHONE }}
            TEACHER_UID: ${{ secrets.TEACHER_UID }}
            TEACHER_NAME: ${{ secrets.TEACHER_NAME }}
            TEACHER_NUMBER: ${{ secrets.TEACHER_NUMBER }}

      - name: Second Retry
        if: ${{ failure() }}
        run: |
          python autoApply.py
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            PHONE: ${{ secrets.PHONE }}
            TEACHER_UID: ${{ secrets.TEACHER_UID }}
            TEACHER_NAME: ${{ secrets.TEACHER_NAME }}
            TEACHER_NUMBER: ${{ secrets.TEACHER_NUMBER }}
